# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Snip < Formula
  desc "A fast, lightweight CLI snippet manager."
  homepage "https://github.com/yellowey-com/snip-cli"
  version "0.16.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yellowey-com/snip-cli/releases/download/v0.16.1/snip-cli_Darwin_x86_64.tar.gz"
      sha256 "e6709e28f5557332a66e4ce71e4a9187d08f1f875f639bcb513f05ae58464f5c"

      define_method(:install) do
        bin.install "snip"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yellowey-com/snip-cli/releases/download/v0.16.1/snip-cli_Darwin_arm64.tar.gz"
      sha256 "c8e137d0fdc8d367f2d259beed6da811222868b4c41b8f07ffd8c78880fca66d"

      define_method(:install) do
        bin.install "snip"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yellowey-com/snip-cli/releases/download/v0.16.1/snip-cli_Linux_x86_64.tar.gz"
      sha256 "84a8b5bb528fb8fc49976167b46a7865be0e346310174b9775258ac399398d50"
      define_method(:install) do
        bin.install "snip"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yellowey-com/snip-cli/releases/download/v0.16.1/snip-cli_Linux_arm64.tar.gz"
      sha256 "2a7a6898b0450044a07f9ff3c2d75dc6cd0cc04fe898284ee394a1372a3836bf"
      define_method(:install) do
        bin.install "snip"
      end
    end
  end
end
