# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Snip < Formula
  desc "A fast, lightweight CLI snippet manager."
  homepage "https://github.com/yellowey-com/snip-cli"
  version "0.16.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yellowey-com/snip-cli/releases/download/v0.16.0/snip-cli_Darwin_x86_64.tar.gz"
      sha256 "2793f8886de4d388db6d1d4a3af4c20ca5c5a49a44ec77c159a299960dab1b71"

      define_method(:install) do
        bin.install "snip"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yellowey-com/snip-cli/releases/download/v0.16.0/snip-cli_Darwin_arm64.tar.gz"
      sha256 "11ddad084f032a9ba176af842f635acd4467459598825cfe315ed5f4103c393c"

      define_method(:install) do
        bin.install "snip"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yellowey-com/snip-cli/releases/download/v0.16.0/snip-cli_Linux_x86_64.tar.gz"
      sha256 "9e75d5bd02e28e8b5c847c0b147bd7831c552328b94c405985d63e15353b2921"
      define_method(:install) do
        bin.install "snip"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yellowey-com/snip-cli/releases/download/v0.16.0/snip-cli_Linux_arm64.tar.gz"
      sha256 "9506303b857d881a074dfb26e158a5834473a062d932c1257590a821c436c2fe"
      define_method(:install) do
        bin.install "snip"
      end
    end
  end
end
